feat(01-Building-blocks): added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -2,19 +2,19 @@ name: 01 - Building Blocks
 
 on: push
 
-jobs:   
+jobs:
     echo-hello:
-            runs-on: ubuntu-latest
-         steps:
-            -name:  Say hello
-            run:  echo "Hello World" 
-
+        runs-on: ubuntu-latest
+        steps:
+           - name: Say Hello
+             run: echo "Hello World"
     echo-goodbye:
         runs-on: ubuntu-latest
         steps:
-            -name: Failed step
-            run: 
-                echo "I will fail"
-                exit 1
-            -name: Say good-bye
-            run: echo "good bye"
+           - name: Failed step
+             run:  |
+              echo "I will fail"
+              exit 1
+           - name: Say goodbye
+             run: echo "Good bye" 
+
